### ISSUE TITLE
Nearest neighbors on knowledge graph embedding PaCMAP reduction did not work well

### ISSUE THREAD

**Issue by KnutJaegersberg** [YingfanWang/PaCMAP#26]
Hi, I applied PaCMAP on pretrained knowledge graph embeddings made from wikidata5m knowledge graph (https://graphvite.io/docs/latest/pretrained_model.html). These are quite chunky and looking up nearest neighbors eats JUST works within my swap limits, but is very slow (so I know it works and the quality of the embedding nearest neighbors is good). I tried RcppHNSW to build an index, but that did not work. So I thought I try PaCMAP. Results were not usable, how can I learn more how to use PaCMAP for this use case? How reliable are nearest neighbors with PaCMAP?

**Comment by hyhuang00** [comment]
Could you elaborate more on how the PaCMAP results are and why are they non-usable? PaCMAP is not a nearest neighbor finding algorithm -- it relies on the [AnnoyIndex](https://github.com/spotify/annoy) to build the nearest neighbor index for constructing the pairs.

**Comment by hyhuang00** [comment]
I see your concern here. PaCMAP, while being robust to a bunch of parameters, still depends on the distance metric in the original space. In your case where the original space comes from a graph embedding, I suppose that you may want to use the cosine similarity for PaCMAP as well (it can be easily done by `reducer = pacmap.PaCMAP(distance='angular')`). Sorry for not mentioning it in the README file, as this is a fairly new feature that has been just added.

Regarding the nearest neighbors, since PaCMAP generally reduces embeddings down to 2D, the lower dimensional space will inevitably lose some local structure in the original space, so sometimes it could be less meaningful, especially if you only look at top-2 neighbors or so.

**Comment by KnutJaegersberg** [comment]
Thanks a lot for clarifying!

**Comment by hyhuang00** [comment]
@KnutJaegersberg Have you obtained the results you wanted to see from PaCMAP? Personally I haven't tried using angular distance yet.

**Comment by KnutJaegersberg** [comment]
nearest neighbor search didnt work yet as originally hoped. Nonetheless thank you! I have a better feeling now for what to use PaCMAP. 

     keyword     aristide      laffite      phisher  gulf_arabic    schiavone haussmannian        qatar 
0.000000e+00 1.525113e-12 2.602030e-12 1.267253e-11 3.162060e-11 1.385767e-10 3.707257e-10 5.530758e-10 
   oubliette    yossarian 
8.295673e-10 9.479953e-10
