### ISSUE TITLE
Segmentation fault when running model in loop

### ISSUE THREAD

**Issue by lennartnicolas** [YingfanWang/PaCMAP#44]
I wanted to run the model on several subsets in a basic loop which causes several errors including segmentation fault. E.g. UMAP is not causing any problems. Any workarounds or suggestions how to solve that?

**Comment by hyhuang00** [comment]
It's hard to distinguish the root cause of segmentation fault since it can be caused by errors on multiple levels. The current version on GitHub and PyPI passed all test cases on an Intel machine and a Macbook without segfault. One case I have met before is that the computing machine does not support the instruction set used by numba. This error usually happens when the machine you used to compute is not the same as the machine you used for compiling PaCMAP. I would recommend you to remove the cache by removing .pycache directory under the folder where you install PaCMAP, and try to run PaCMAP again.

**Comment by zeitderforschung** [comment]
The numpy array in the [vecs_1716228262.zip](https://github.com/YingfanWang/PaCMAP/files/15380958/vecs_1716228262.zip) causes randomly a segmentation fault when called within docker.

```python
import numpy as np
from pacmap import PaCMAP

vecs = np.load("vecs_1716228262.npy")
print(PaCMAP(n_components=2, random_state=42).fit_transform(vecs))
```
